### ISSUE TITLE
Loan.new with named parameters

### ISSUE THREAD

**Issue by jeremyf** [kolosek/finance_math#1]
First, looks like a very help, yet simple library. Kudos on narrow scope.

Given that you can initialize with up to 5 parameters (or more) it would be helpful to have those parameters named.

```ruby
Loan.new(10.5, 12, 15000)
```

When I look at the above, I don't know which parameter maps to which concept.

**Comment by kolosek** [comment]
That's an excellent comment, thanks. I'll include it in next release.
