### ISSUE TITLE
Consider avoiding the use of floats for financial computations

### ISSUE THREAD

**Issue by jeremyf** [kolosek/finance_math#2]
Float values are prone to rounding errors, http://stackoverflow.com/questions/960072/rounding-errors.

The RubyMoney/money gem has moved from Floats to [BigDecimal](http://ruby-doc.org/stdlib-2.2.0/libdoc/bigdecimal/rdoc/BigDecimal.html) and explains why:

> The Money#dollars and Money#amount methods now return instances of BigDecimal
> rather than Float. We should avoid representing monetary values with floating
> point types so to avoid a whole class of errors relating to lack of precision.
> There are two migration options for this change:
> - The first is to test your application and where applicable update the
>   application to accept a BigDecimal return value. This is the recommended
>   path.
> - The second is to migrate from the #amount and #dollars methods to use the
>   #to_f method instead. This option should only be used where Float is the
>   desired type and nothing else will do for your application's requirements.
> 
> From [money gem's Migration Notes](https://github.com/RubyMoney/money#migration-notes)

**Comment by kolosek** [comment]
There is difference between BigDecimal and float:

  expected: 42.82076503747119
            got: 42.820765037470125

**Comment by bf4** [comment]
Legally, floats are fine, as the tolerance for APR is 4 decimals. :shrug:
