### ISSUE TITLE
Mortgage autoload specified, but no code

### ISSUE THREAD

**Issue by bf4** [kolosek/finance_math#3]
https://github.com/kolosek/finance_math/blob/241f594dbf19e0d9f899295f5622d968219b6ab2/lib/finance_math.rb

https://github.com/kolosek/finance_math/tree/241f594dbf19e0d9f899295f5622d968219b6ab2/lib/finance_math

:shrug:

**Comment by kolosek** [comment]
Nice catch. It was meant for easier expanding of the functionality of the gem. But it might not be as self-explanatory.

**Comment by bf4** [comment]
oh
