### ISSUE TITLE
Calculate number of periods to accomplish a loan

### ISSUE THREAD

**Issue by kandebonfim** [kolosek/finance_math#6]
I'm having a hard time trying to do this. I basically have **monthly payment**, **future value**, **present value** and the **interest rate** and I want to calculate the number of periods to finish the loan in these conditions.

Is that possible?

**Comment by kolosek** [comment]
This gem is not designed to do that. If some user skips one monthly payment, his number of periods would increase dynamically, and this gem is about fixed pre-set number of periods.

**Comment by kandebonfim** [comment]
Found [this gem](https://github.com/randallreedjr/time_value) that solved my problem.
